# Generated by Django 4.1.3 on 2022-11-10 11:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_name', models.CharField(max_length=48, verbose_name='Имя актера')),
                ('staff_id', models.IntegerField(unique=True, verbose_name='Id человека на кинопоиске')),
                ('year_of_birth', models.SmallIntegerField(verbose_name='Год рождения')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Человека',
                'verbose_name_plural': 'Люди',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=24, verbose_name='title')),
                ('subtitle', models.CharField(max_length=24, verbose_name='subtitle')),
                ('text', models.TextField(verbose_name='text')),
                ('is_published', models.BooleanField(default=False, verbose_name='is published')),
                ('date_published', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='URL')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='author')),
            ],
            options={
                'verbose_name': 'пост',
                'verbose_name_plural': 'посты',
                'db_table': 'blog_posts',
                'ordering': ('date_published',),
            },
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('film_name', models.CharField(max_length=48, verbose_name='Название фильма')),
                ('film_id', models.IntegerField(unique=True, verbose_name='id фильма на кинопоиске')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('film_poster', models.ImageField(blank=True, upload_to='images', verbose_name='Постер')),
                ('release_year', models.SmallIntegerField(verbose_name='Год выпуска')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='URL')),
                ('actors_in_film', models.ManyToManyField(default=None, to='user.staff')),
            ],
            options={
                'verbose_name': 'Название фильма',
                'verbose_name_plural': 'Фильмы',
            },
        ),
    ]
